### ISSUE TITLE
Support annotations a la Sketchfab's model viewer

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#334]
Sketchfab has a cool feature where users can annotate positions in 3D space with labels and markers that allow users to get detail about highlights of the model, and also change the camera perspective / controls scheme as they cycle through active annotations.

**Comment by cdata** [comment]
@yuinchien is going to work on some mocks for this feature.

**Comment by soraryu** [comment]
Is there anything to look at in regards to those mocks?

**Comment by cdata** [comment]
@soraryu here are some early mocks. These are just an exploration, and we have a more thorough UX exploration taking place right now that will iterate on these ideas and introduce new ones.

![unnamed (1)](https://user-images.githubusercontent.com/240083/66416024-c976cc80-e9b1-11e9-848d-cba8877e20b0.png)

![unnamed](https://user-images.githubusercontent.com/240083/66416021-c67bdc00-e9b1-11e9-987e-1df299b12f08.png)

**Comment by soraryu** [comment]
Cool, thanks for sharing! Couple of questions/comments if I may:
- would be great if occlusion behaviour would be configurable (e.g. how does a number 4 on the backside behave)
- will these be html or 3D or a combination? (e.g. for occlusion I guess it would need to be 3D)
- a special case for annotations is when some are very far away (in those cases they might need to be merged with nearby ones, or there's a smaller LOD (e.g. a dot, similar to what Google Maps is doing)
- another similar but sightly different case is when a model is rotated in a way that two overlap; they might also need to be merged

Is that purely a design test or is there already a branch to look at?
(just asking because we're in need of that now, and considering either to inject into threejs behind model-viewer or waiting for a proper way)

**Comment by cdata** [comment]
> would be great if occlusion behaviour would be configurable (e.g. how does a number 4 on the backside behave)

Great feedback, thanks!

> will these be html or 3D or a combination? (e.g. for occlusion I guess it would need to be 3D)

The intention is for it to be a combination. The "annotations" (the descriptive part) will be DOM and the "hotspot" (the circle with the number) will be GL and have relatively limited customization options (you can set an image, show a number, configure colors and maybe custom shapes).

> a special case for annotations is when some are very far away (in those cases they might need to be merged with nearby ones, or there's a smaller LOD (e.g. a dot, similar to what Google Maps is doing)

This is very interesting. We will definitely take this into consideration, although my gut tells me that #738 will be necessary for addressing this use case.

> another similar but sightly different case is when a model is rotated in a way that two overlap; they might also need to be merged

Can you give a concrete example of this case? I'm interested in understanding it better.

> Is that purely a design test or is there already a branch to look at?

I'm sad to say it's just a concept right now. We know this is a hotly anticipated feature with a lot of demand. My best estimate for when it will be implemented is Q1 2020, so if you need it right now you'll have to help yourself. I am happy to answer questions about our code base if you are confident enough to try to build it for yourself.

**Comment by cdata** [comment]
Here is another mock from the original UX exploration:

![190522 model-viewer annotation 2019-10-08 14_37_21](https://user-images.githubusercontent.com/240083/66435252-46696c80-e9d9-11e9-9b99-8546aa5d1b99.gif)
