### ISSUE TITLE
User configurable interaction policy

### ISSUE THREAD

**Issue by srussking** [GoogleWebComponents/model-viewer#500]
The new interaction "allow-when-focused" policy which allows for scrolling over the model is cool, however, for my purposes it is a difficult to convey to the user, also it seems to get reset every time the user "fullscreens" the app or contracts (possibly this is due to our putting it into an iframe, unknown...).

I am wondering if it is possible to have that be an attribute that is passed in. i.e. <model-viewer ... interaction-policy="always-allow" />

Not familiar enough with the code to submit a pr for that but seems like it should be easy enough to add and be inline with the current strategy.

Just a suggestion though.

**Comment by cdata** [comment]
Thanks for the feedback!

Yes, we want to make most of the controls constraints configurable as public API (a similar issue in this area is #458 ). I would say that the main thing we need to decide is the shape of the API.

`interaction-policy` is a reasonable name for an attribute that controls this, although I would love to hear ideas from other folks in the community if they have any.

For your specific use case @srussking it might help mitigate the problem if you manually re-focus the `<model-viewer>` when fullscreen state changes e.g., by calling `yourModelViewer.focus()`.

But in general I agree that we need to support changing the interaction policy because the default is best for non-fullscreen use cases.

**Comment by srussking** [comment]
Cool, wanted to update this in case anyone else has this issue. Moving the fullscreen div inside the model-viewer made this issue less problematic, such that now fullscreen and back to normal keeps the focus on the model viewer...

Cheers

**Comment by cdata** [comment]
I also want to call out that this is related to https://github.com/GoogleWebComponents/model-viewer/issues/479 which would enable a less strict heuristic for enabling interaction that might serve as a middle-ground between "always" and "only when focused."

**Comment by cdata** [comment]
This has been fixed in #621
