### ISSUE TITLE
Fidelity tests are broken

### ISSUE THREAD

**Issue by elalish** [GoogleWebComponents/model-viewer#508]
### Description

Using npm run check-fidelity results in white images with a progress bar:
![Screenshot from 2019-04-26 10-48-51](https://user-images.githubusercontent.com/1649964/56835062-0302b380-6828-11e9-81aa-f3db43ee046b.png)

Sounds like this might be related to #487.

### OS

- [ ] Android
- [ ] iOS
- [x ] Linux
- [ ] MacOS
- [ ] Windows

### Versions
Latest master:
- model-viewer: 0.3.1
- three.js: 0.101.1

**Comment by cdata** [comment]
Thanks for reporting @elalish 🙇 

I think the fix for this might be as easy as changing this to listen to the `model-visibility` event (and double checking that `event.detail.visible` is `true`): https://github.com/GoogleWebComponents/model-viewer/blob/d9b2cc2caaacc35d31665d4aac92bc88cdb2ff3c/src/test/fidelity/artifact-creator.ts#L186-L189

**Comment by elalish** [comment]
Okay, I'll take a stab at that.
