### ISSUE TITLE
Camera can enter object

### ISSUE THREAD

**Issue by elalish** [GoogleWebComponents/model-viewer#542]
### Description
Really there are two problems here. The first is the near and far plane are set arbitrarily to 0.1 and 10 times the framed height, respectively, which is not enough in all cases. More importantly, zooming the camera moves it physically closer to the center of model, and thus sometimes inside of the model, which can't be fixed by the near plane. I would propose solving this by zooming in by narrowing the FOV and keeping the camera at the ideal radius. 

#### Live Demo
https://maps3d.io/blog/
Just zoom in and you'll soon see something like this:
![Screenshot from 2019-05-09 09-03-50](https://user-images.githubusercontent.com/1649964/57468656-c37d9380-7239-11e9-80b3-e34f7a832f0a.png)

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [x] Linux
- [ ] MacOS
- [ ] Windows

**Comment by cdata** [comment]
>  The first is the near and far plane are set arbitrarily to 0.1 and 10 times the framed height, respectively, which is not enough in all cases.

Just some background: this actually isn't arbitrary. We probably should have left a comment (at the time the assets we were testing could not be mentioned in public). We arrived at these ratios after a lot of empirical observation related to depth precision. We had problematic assets we were testing from NASA and were getting the best results from this range. It might actually be worth us testing the behavior against some of those assets since we are no longer scaling the object as of #526 (I wouldn't be surprised to learn that this has an effect on what we were seeing).

**Comment by cdata** [comment]
Going to flag this as a bug and related to #232

**Comment by elalish** [comment]
Can you point me to the troublesome models? As I start to mess with this, I'd like to make sure they still work.

**Comment by cdata** [comment]
I will send one to you offline. It's 30MB and can't be attached to this thread unfortunately.

**Comment by pushmatrix** [comment]
Hmm we seem to run into this with a few of our models as well. Especially the ones where there are hanging parts not near the center of the object

**Comment by elalish** [comment]
@cdata I think this is important for 1.0.
