### ISSUE TITLE
Seamless poster transitions: configure model to fit desired CSS pixel rect

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#599]
One of my favourite 3D examples on the web is from Panic: https://panic.com/transmit/

![transmit](https://user-images.githubusercontent.com/190692/58836283-656c8200-8626-11e9-9852-c236f79ee191.gif)

It's the perfect progressive enhancement. It starts off as an image of the truck, and then when the 3D model is loaded it swaps out the image for the 3D and you don't notice it at all. I'd like to explore what that would look like for model-viewer.

The main issue I see is with supporting different aspect ratios. The aspect ratio can make it tricky to line the poster up seamlessly with the rendered model.

@cdata suggests that it is theoretically possible with a combination of "background-size: cover" and "camera-orbit". You would need to adjust the "camera-orbit" attribute to ensure that the model is the same pixel size regardless of aspect ratio.

Let's see if it's possible to add a public method to make adjusting the camera orbit based on desired CSS pixel size a thing.

**Comment by cdata** [comment]
cc @elalish

**Comment by elalish** [comment]
I like this idea, though I'm not entirely following the method of solution. I could imaging that you take a screenshot of the render on a transparent background with a tight-ish bounding box, then place and scale that image appropriately within the runtime-sized model-viewer box for alignment, while rendering the background behind it normally. I think we could automatically determine the placement values based on the width and height of the input image, since that would match the model-viewer state when it was captured.

**Comment by elalish** [comment]
@cdata I would love to include this for 1.0. I understand if it doesn't make the cut, but it seems doable.

**Comment by pushmatrix** [comment]
Would be great to have this included as a milestone before 1.0 as we'll be relying heavily on it.
