### ISSUE TITLE
Interaction policy ignored

### ISSUE THREAD

**Issue by hjeldin** [GoogleWebComponents/model-viewer#717]
### Description

Interaction policy = 'always-allow' is currently ignored for both iOS/Safari and Android/Chrome running the latest version available on unpkg.

```
<model-viewer 
     id="modelLoader"
     src="https://cdn.glitch.com/36cb8393-65c6-408d-a538-055ada20431b/Astronaut.glb?
1542147958948"
     alt="A 3D model of an astronaut"
     background-color="#70BCD1"
     shadow-intensity="1"
     camera-controls
     interaction-policy="always-allow"
     interaction-prompt="auto"
     auto-rotate ar magic-leap></model-viewer>
```

A workaround for android is to focus automatically when a 'load' event is received, but it doesn't work on newer versions of Safari since, i presume, they now require user input to actually trigger a focus event:
```
<script>
      document.getElementById('modelLoader').addEventListener('load', function () {
        this.focus();
      });
</script>
```

Our current workaround for both iOS and Android is by using the version of model-viewer that is being currently used @ https://googlewebcomponents.github.io/model-viewer/ which isn't affected by this issue.

#### Live Demo

https://glitch.com/edit/#!/melon-pink

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [X] Safari

### OS

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.5.1
- three.js: rXX

**Comment by cdata** [comment]
@hjeldin yes,  my apologies. The way we deploy our docs is a little confusing because they aren't versioned, and they always update with whatever is on `master. We should either version them, or only deploy them when we do a release.

`interaction-policy` will be introduced in v0.6.0 which should be released on Monday. In the mean time, the version of the library on our docs page is very close to what will be released, so feel free to use that 👍

**Comment by hjeldin** [comment]
Can confirm: issue is fixed in v.0.6.0, thanks!
