### ISSUE TITLE
Checking for support for rel=ar attribute to detect iOS QuickLook?

### ISSUE THREAD

**Issue by cwervo** [GoogleWebComponents/model-viewer#776]
Based on [the last section — titled **Feature Detection** — in this WebKit blog post](https://webkit.org/blog/8421/viewing-augmented-reality-assets-in-safari-for-ios/), it looks like the WebKit recommended way to detect iOS's AR QuickLook feature is by checking if anchors support the `ar` value for `rel`.

Here's a [a Glitch website I made](https://test-ios-quicklook-js.glitch.me/quicklook-available.html) that just runs:

```javascript
// ------ function from script.js ------
function detectiOSARQuickLook() {
    const testAnchor = document.createElement("a");
    return testAnchor.relList.supports("ar")
}
```

& produces:

| Desktop (MacOS Mojave, 10.14.6) | Mobile (iPhone 11 Pro, iOS 13.1) |
| ------------- | ------------- |
| ![Screen Shot 2019-09-26 at 11 29 05 PM](https://user-images.githubusercontent.com/5826638/65740127-b90f4980-e0b5-11e9-9d67-f1795a432733.png)  | ![IMG_0446](https://user-images.githubusercontent.com/5826638/65740087-8feeb900-e0b5-11e9-9ce4-dcbe7f5b5b3e.PNG)  |

This would be the most correct way to set `canLaunchQuickLook` in `ar.ts` — would it be useful to make a PR for this? I imagine this would also future-proof `model-viewer` if MacOS ever supports AR QuickLook somehow.

**Comment by cdata** [comment]
Thanks for the suggestion! In fact, [we already perform this detection](https://github.com/GoogleWebComponents/model-viewer/blob/master/src/constants.ts#L60-L66). Unfortunately, reality is a little more complicated. For some versions of Chrome on iOS, the detection passes but Quick Look only launches as expected if the correct `Content-Type` header is served with the file. WebKit claims that setting `Content-Type` correctly is a universal requirement, but as of right now Safari does not enforce this requirement. We were able to convince iOS Chrome team to switch to Safari's behavior, but for the time being we are performing browser-specific detections in order to support the ability to opt-out manually from Chrome or Safari on iOS (via the `quick-look-browsers` attribute).

**Comment by cdata** [comment]
Related: https://github.com/GoogleWebComponents/model-viewer/issues/534

**Comment by cwervo** [comment]
Ahhh, okay, I didn't realize all the context around undefined behavior based on (un)set `Content-Type` — thanks!
